# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_c <- function(beta, lambda) {
    .Call(`_ACBalancing_soft_c`, beta, lambda)
}

objvalue <- function(X, beta, lambda) {
    .Call(`_ACBalancing_objvalue`, X, beta, lambda)
}

proximaloptim <- function(X, rate, lambda, beta_start, convergence, iteration) {
    .Call(`_ACBalancing_proximaloptim`, X, rate, lambda, beta_start, convergence, iteration)
}

